### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Azurion42** [vektor9999/NolvusDashboard#1]
I know this isn't an issue, per-say, but I was wondering if there were any plans to have a Linux dashboard eventually? I don't know if the way it is right now would even be possible to install on linux via proton/wine. It looks amazing, but I just don't know if I could get it working properly.

**Comment by rafaelrgazquez** [comment]
+1 for this
I'm trying to make it run on Linux right now.
What are the dependencies for this tool?

EDIT:
I think I got in the code dotnet462, maybe installing dotnet48 on its Proton prefix might work?

**Comment by Gaspd** [comment]
Yo,

I'm on Arch

wine 8.18-1
winetricks-git 20230212.r44.g556ad353-1

I did quick workaround, commented if statement for path validation length > 10, and got NolvusUpdater.exe from that.

After that i still got exception with, i think, references. So i opened winetricks --gui and installed windows components.
Right now i have:
- dxvk
- d3dx9
- dotnetcore3
- dotnet462
- vcrun2015-2022

For now  i kind of launched Updater and DashBoard, pasted Nexus API key and logged in with Nolvus account, but when the auto installer starts it throws exception.

`
System.Management.ManagementException: Error code: 0x80041002
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.PropertyDataCollection.get_Item(String propertyName)
   at Vcc.Nolvus.Services.Globals.GlobalsService.GetVideoAdapters()
   at Vcc.Nolvus.Dashboard.Frames.Installer.PerformanceFrame.OnLoad()
   at Vcc.Nolvus.Core.Frames.DashboardFrame.Initialize[T]()
   at Vcc.Nolvus.Dashboard.DashboardWindow.LoadFrame[T](FrameParameters Parameters)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at Vcc.Nolvus.Components.Controls.FlatButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by rafaelrgazquez** [comment]
I'm also on Arch, using Proton 8-04 inside Steam
I've got that far but I did a few things different:

- Instead of dotnet462, I installed dotnet48 using protontricks (had to init the prefix with proton 5.0 and then changed to proton 8.0-4)
- Didn't install dotnetcore3
- Installed .Net Desktop Runtime 5 (win x64), using official installer as instructed
- Installed .Net SDK 6 (win x64), using official installer as instructed

I've got an issue that a lot of screens don't have fonts but they mostly work until you select the game related settings (where somehow the fonts worked), after that the app will just close without errors.

I've also tried manual installation which took me more than a week and it's REALLY tedious. I couldn't get Grass Precache to work, it just CTD as soon as it finishes loading.

**Comment by jccpalmer** [comment]
I'm really interested in this, too, as right now, I reboot to Windows to play Nolvus. Not a big deal, but a nuisance. I was going to tinker with the auto-installer (I'm on Nobara), see if it might work in Bottles. Long shot, but since you all have tried your routes, I might as well see what Bottles can do.

**Comment by jccpalmer** [comment]
+1 from me.

I was able to get the installer to launch in a Bottle, but it didn't like my path, saying it was too long, so no go there. You two got a lot further than me.

**Comment by rafaelrgazquez** [comment]
Oh! Yep, I did a workaround for this.
Go to your wine prefix/dosdevices and run `ln -s /path/to/nolvus/dir d:` (you can find it inside `~/.var/app/com.usebottles.bottles/data/bottles/bottles/`)
This will create a `D:` drive in wine where you can install Nolvus with a small path.
In my case, it was: `ln -s /home/rafaelroque/Library/Nolvus d:`

Just remember, Bottles needs to have access to this path or Flatpak will stop it. Run `flatpak override com.usebottles.bottles --filesystem=/path/to/nolvus/dir`

**Comment by ChristianHardin** [comment]
# Using Bottles

I managed to complete the installer by using this path ```drive_c/Nolvus/NolvusUpdator.exe```.

After the install I cant get the dashboard to fully launch. The process will exists, but nothing else happens.

What I have installed in the prefix (using wine-ge-proton8-22):
- .Net5
- VC redist

Ill keep trying different dependencies and wine versions to see if I can get anything running.

# Using winetricks

Ill spend more time on this at a later date but same situation as with bottles. But this time with wine-8.20 and I got an error.
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Resource 'blank.bmp' was not found.
  at System.Drawing.Bitmap..ctor (System.Type type, System.String resource) [0x0004d] in <b58d88bd041145279c2003cf306f84d5>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap..ctor(System.Type,string)
  at Syncfusion.Windows.Forms.Tools.ToolStripEx..ctor (System.Windows.Forms.ToolStripRenderer renderer) [0x00201] in <3bfb02f7297e4edf8ed54823d0ee1dc5>:0 
  at Syncfusion.Windows.Forms.Tools.ToolStripEx..ctor () [0x00007] in <3bfb02f7297e4edf8ed54823d0ee1dc5>:0 
  at Syncfusion.Windows.Forms.Tools.ToolStripPanelItem+ToolStripInternal..ctor (System.Boolean bUseStandardLayout) [0x0000e] in <3bfb02f7297e4edf8ed54823d0ee1dc5>:0 
  at (wrapper remoting-invoke-with-check) Syncfusion.Windows.Forms.Tools.ToolStripPanelItem+ToolStripInternal..ctor(bool)
  at Syncfusion.Windows.Forms.Tools.ToolStripPanelItem..ctor (System.Boolean bUseStandardLayout) [0x0002c] in <3bfb02f7297e4edf8ed54823d0ee1dc5>:0 
  at Syncfusion.Windows.Forms.Tools.ToolStripPanelItem..ctor () [0x00000] in <3bfb02f7297e4edf8ed54823d0ee1dc5>:0 
  at (wrapper remoting-invoke-with-check) Syncfusion.Windows.Forms.Tools.ToolStripPanelItem..ctor()
  at Vcc.Nolvus.Dashboard.DashboardWindow.InitializeComponent () [0x00010] in <ee07a9a1c8834030b3166e1d8d1bd4e6>:0 
  at Vcc.Nolvus.Dashboard.DashboardWindow..ctor () [0x0000e] in <ee07a9a1c8834030b3166e1d8d1bd4e6>:0 
  at (wrapper remoting-invoke-with-check) Vcc.Nolvus.Dashboard.DashboardWindow..ctor()
  at Vcc.Nolvus.Dashboard.Program.LoadApp () [0x00058] in <ee07a9a1c8834030b3166e1d8d1bd4e6>:0 
01b4:fixme:thread:QueryThreadCycleTime (000000000000017C,00007F624F9EFD58): stub!
...
```
Probably a missing dependency, but I don't have time to work on this right now.
